FROM ubuntu:24.04

# Set environment variables
ENV IBC_VERSION=3.22.0
ENV IB_GATEWAY_VERSION=stable
ENV HOME=/home/ibgateway
ENV IBC_PATH=/opt/ibc

WORKDIR /tmp/setup

# Install required dependencies
RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes \
    curl \
    ca-certificates \
    unzip socat\
    xvfb x11vnc && \
    # Create home directory and user
    useradd -ms /bin/bash ibgateway && \
    # Download and install IB Gateway
    curl -sSOL https://download2.interactivebrokers.com/installers/ibgateway/stable-standalone/ibgateway-stable-standalone-linux-x64.sh && \
    chmod +x ibgateway-stable-standalone-linux-x64.sh && \
    ./ibgateway-stable-standalone-linux-x64.sh -q -dir /home/ibgateway/Jts/ibgateway/stable && \
    rm -f ibgateway-stable-standalone-linux-x64.sh && \
    # Download and install IBC
    curl -sSOL https://github.com/IbcAlpha/IBC/releases/download/${IBC_VERSION}/IBCLinux-${IBC_VERSION}.zip && \
    mkdir -p ${IBC_PATH} && \
    unzip ./IBCLinux-${IBC_VERSION}.zip -d ${IBC_PATH} && \
    find ${IBC_PATH} -type f -name "*.sh" -exec chmod u+x {} \; && \
    mkdir -p ${HOME}/ibc && \
    cp ${IBC_PATH}/config.ini ${HOME}/ibc/ && \
    chown -R ibgateway:ibgateway ${HOME} ${IBC_PATH} && \
    # Clean up
    apt-get remove --yes unzip curl && \
    apt-get autoremove --yes && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/setup/*

# Copy start script
COPY --chown=ibgateway:ibgateway ./run.sh ${HOME}/run.sh

RUN chmod +x ${HOME}/run.sh

USER ibgateway
WORKDIR ${HOME}

EXPOSE ${IB_PORT}

# Start run script
CMD ["/home/ibgateway/run.sh"]